name: zentrio_admin
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shadcn_ui: ^0.11.0
  responsive_framework: ^1.4.0
  flutter_form_builder: ^9.4.0
  signals: ^5.5.0
  form_builder_validators: ^11.0.0
  auto_route: ^9.2.0
  go_router: ^14.2.7
  get_it: ^7.7.0
  injectable:
  shared_preferences: ^2.3.1
  dio: ^5.5.0+1
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.4.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  dart_jsonwebtoken: ^2.14.0
  flutter_dropzone: ^4.0.2
  tuple: ^2.0.2
  freezed: ^2.5.7
  awesome_flutter_extensions: ^1.2.0
  json_view: ^0.4.2
  flutter_json_view: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  go_router_builder: ^2.3.0
  injectable_generator:
  flutter_lints: ^4.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
